/**
 * Bildband (Picture Book) data types and constants for Wurzelwanderer.
 * A Bildband is a 10-scene illustrated fairy tale story in rhymes.
 */

import type { GenerierterBekannter } from './merkmale';
import type { GespeicherteRegion } from './regionen';
import type { Naturell } from './naturelle';

/** Scene types for the 10-part story structure */
export type SzenenTyp =
	| 'ort_einfuehrung'
	| 'anfang'
	| 'problem'
	| 'ziel'
	| 'verfolgung'
	| 'ortswechsel'
	| 'neuer_ort'
	| 'twist'
	| 'ueberwindung'
	| 'abschluss';

/** Story structure definition */
export interface SzenenDefinition {
	typ: SzenenTyp;
	nummer: number;
	titel: string;
	beschreibung: string;
	promptHinweis: string; // Hint for the LLM about this scene
}

/** The 10-part story structure */
export const SZENEN_STRUKTUR: SzenenDefinition[] = [
	{
		typ: 'ort_einfuehrung',
		nummer: 1,
		titel: 'Der Ort',
		beschreibung: 'Wo sich das Ganze befindet',
		promptHinweis: 'Beschreibe den Startort atmosphärisch und stimmungsvoll. Führe den Leser in die Welt ein.'
	},
	{
		typ: 'anfang',
		nummer: 2,
		titel: 'Die Gefährten',
		beschreibung: 'Wer dabei ist, Vorstellung der Charaktere',
		promptHinweis: 'Stelle die Hauptcharaktere vor - ihre Eigenschaften, ihr Aussehen, was sie gerade tun.'
	},
	{
		typ: 'problem',
		nummer: 3,
		titel: 'Das Problem',
		beschreibung: 'Ein Problem taucht auf',
		promptHinweis: 'Etwas Unerwartetes passiert - eine Bedrohung, ein Rätsel, ein Konflikt entsteht.'
	},
	{
		typ: 'ziel',
		nummer: 4,
		titel: 'Das Ziel',
		beschreibung: 'Die Charaktere setzen sich ein Ziel',
		promptHinweis: 'Die Charaktere entscheiden sich, etwas dagegen zu tun. Sie fassen einen Plan.'
	},
	{
		typ: 'verfolgung',
		nummer: 5,
		titel: 'Der Weg',
		beschreibung: 'Wie sie das Ziel verfolgen',
		promptHinweis: 'Die Charaktere machen sich auf den Weg oder beginnen mit der Umsetzung ihres Plans.'
	},
	{
		typ: 'ortswechsel',
		nummer: 6,
		titel: 'Die Reise',
		beschreibung: 'Sie gehen zu einem anderen Ort',
		promptHinweis: 'Die Reise zu einem neuen Ort - Übergang, Veränderung der Umgebung.'
	},
	{
		typ: 'neuer_ort',
		nummer: 7,
		titel: 'Neues Land',
		beschreibung: 'Was dort so ist',
		promptHinweis: 'Beschreibe den neuen Ort - seine Besonderheiten, Atmosphäre, was die Charaktere dort vorfinden.'
	},
	{
		typ: 'twist',
		nummer: 8,
		titel: 'Die Wendung',
		beschreibung: 'Ein Twist oder neues Problem',
		promptHinweis: 'Etwas Unerwartetes passiert - eine Überraschung, ein Hindernis, eine Enthüllung.'
	},
	{
		typ: 'ueberwindung',
		nummer: 9,
		titel: 'Der Triumph',
		beschreibung: 'Wie sie es überwinden',
		promptHinweis: 'Die Charaktere meistern die Herausforderung - durch Mut, Klugheit, Zusammenhalt.'
	},
	{
		typ: 'abschluss',
		nummer: 10,
		titel: 'Das Ende',
		beschreibung: 'Abschluss der Geschichte',
		promptHinweis: 'Ein würdiger Abschluss - Rückkehr verändert, mit etwas Neuem, oder sie bleiben/gehen weiter. Ein Fazit.'
	}
];

/** A single scene in the picture book */
export interface BildbandSzene {
	nummer: number;
	typ: SzenenTyp;
	titel: string;
	reim: string; // The rhyming text (4-8 lines)
	bilder: string[]; // Array of Base64 image URLs (like locations)
	aktivBildIndex: number; // Which image is currently shown
	region?: GespeicherteRegion;
	ort?: Naturell;
	userKommentar?: string; // Optional user comment for regeneration
	bildFehler?: boolean; // True if image generation failed
}

/** Pre-planned story outline generated by LLM */
export interface StoryPlan {
	zusammenfassung: string; // Overall story summary
	szenenPlaene: string[]; // 10 scene summaries/outlines
	hauptkonflikt: string; // Main conflict
	moral?: string; // Optional moral of the story
	charakterEinfuehrungen: string[][]; // Which characters appear in each scene (by name)
}

/** Status of a Bildband */
export type BildbandStatus = 'in_progress' | 'completed';

/** A complete saved picture book */
export interface GespeicherterBildband {
	id: string;
	titel: string; // Generated by Gemini
	beschreibung: string; // Short description by Gemini
	charaktere: GenerierterBekannter[];
	bekannte: GenerierterBekannter[]; // NPCs in the story
	startRegion: GespeicherteRegion;
	startOrt: Naturell;
	zweiterOrt?: {
		region: GespeicherteRegion;
		ort: Naturell;
	};
	storyPlan?: StoryPlan; // Pre-planned story
	szenen: BildbandSzene[];
	erstelltAm: string; // ISO timestamp
	letzteAktualisierung?: string; // ISO timestamp for last update
	coverBild?: string; // First image as cover
	status: BildbandStatus; // Generation status
}

/** Context for scene generation */
export interface SzenenKontext {
	charaktere: GenerierterBekannter[];
	bekannte: GenerierterBekannter[]; // NPCs that appear in the story
	aktuelleRegion: GespeicherteRegion;
	aktuellerOrt: Naturell;
	zweiterOrt?: {
		region: GespeicherteRegion;
		ort: Naturell;
	};
	bisherigeSzenen: BildbandSzene[];
	szenenDefinition: SzenenDefinition;
	storyPlan?: StoryPlan; // The overall story plan for context
	userAnmerkung?: string;
}

/** Progress callback for bildband generation */
export interface BildbandProgress {
	aktuellerSchritt: number;
	gesamtSchritte: number;
	phase: 'reim' | 'bild' | 'metadaten';
	szene?: BildbandSzene;
}

/** Storage key for saved picture books */
export const BILDBAND_STORAGE_KEY = 'wurzelwanderer-bildbaende';

/** Helper to create an empty scene */
export function erstelleLeereSzene(definition: SzenenDefinition): BildbandSzene {
	return {
		nummer: definition.nummer,
		typ: definition.typ,
		titel: definition.titel,
		reim: '',
		bilder: [],
		aktivBildIndex: 0,
		bildFehler: false
	};
}

/** Helper to get scene definition by type */
export function getSzenenDefinition(typ: SzenenTyp): SzenenDefinition {
	const definition = SZENEN_STRUKTUR.find((s) => s.typ === typ);
	if (!definition) {
		throw new Error(`Unknown scene type: ${typ}`);
	}
	return definition;
}

/** Helper to get scene definition by number (1-10) */
export function getSzenenDefinitionByNummer(nummer: number): SzenenDefinition {
	const definition = SZENEN_STRUKTUR.find((s) => s.nummer === nummer);
	if (!definition) {
		throw new Error(`Invalid scene number: ${nummer}`);
	}
	return definition;
}
